services:
  redis:
    image: redis:alpine
    ports: 
      - "${REDIS_PORT}:6379"
  
  postgres: 
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

    ports: 
      - "${DB_PORT}:5432"

  nginx:
    image: 